#!/usr/bin/python
# -*- coding: utf-8 -*-

PROCESS_ID_INVALID = -1
PROCESS_ID_LOGIN = 0
PROCESS_ID_LOG   = 1

PROCESS_STATE_INVALID = -1
PROCESS_STATE_EMPTY   = 0
PROCESS_STATE_OPEN    = 1
PROCESS_STATE_RUNNING = 2
PROCESS_STATE_SAVE    = 3
