#!/usr/bin/python
# -*- coding: utf-8 -*-

SERVICE_ID_INVALID = -1
SERVICE_ID_LOGIN = 0
SERVICE_ID_LOG   = 1
SERVICE_ID_BILLING   = 2
SERVICE_ID_SCENE = 3
SERVICE_ID_DB   = 4

SERVICE_STATE_INVALID = -1
SERVICE_STATE_EMPTY   = 0
SERVICE_STATE_OPEN    = 1
SERVICE_STATE_RUNNING = 2
SERVICE_STATE_SAVE    = 3
