#!/usr/bin/python
# -*- coding: utf-8 -*-

#########账号登录相关########
MESSAGE_TYPE_INVALID = -1
MESSAGE_TYPE_REQUESTHTTP = 0
MESSAGE_TYPE_ACCOUNTVERIFY_REQ = 1
MESSAGE_TYPE_ACCOUNTVERIFY_RET = 2
MESSAGE_TYPE_ACCOUNTVALIDATE_REQ = 3
MESSAGE_TYPE_ACCOUNTVALIDATE_RET = 4
MESSAGE_TYPE_ACCOUNTSTATE_CHECK = 5
MESSAGE_TYPE_QUEUE_FINISH = 6
MESSAGE_TYPE_ACCOUNT_OFFLINE = 7

MESSAGE_TYPE_PLAYERENTERWORLD = 1001
MESSAGE_TYPE_PLAYERENTERSCENE = 1002

#########DB相关########
MESSAGE_TYPE_ASSIGN_DBTASK = 10001
MESSAGE_TYPE_ASKCHARLIST = 10002
MESSAGE_TYPE_RETCHARLIST = 10003
MESSAGE_TYPE_CREATECHAR = 10004
MESSAGE_TYPE_RETCREATECHAR = 10005
MESSAGE_TYPE_SAVEGUID = 10006

