#!/usr/bin/python
# -*- coding: utf-8 -*-

class Table_ServerConfigList:
    def __init__(self):
        self.__ID__ = 0
        self.Id = 0
        self.StartTime = ''
        self.StartTimeForExpLimit = ''
        self.SelfIp = ''
        self.PortForClient = 0
        self.PortForGMI = 0
        self.MemList = ''
        self.MemOpen = 0
        self.ThreadCount = 0
        self.DBName = ''
        self.DBUser = ''
        self.DBPsw = ''
        self.DBIp = ''
        self.DBPort = 0
        self.DBThreadCount = 0
        self.MaxOnlinePlayingPlayer = 0
        self.MaxOnlineQueuingPlayer = 0
        self.MergeStatus = 0
        self.MergeServerCount = 0
        self.CDKeyOpen = 0
        self.ChongZhiStartTime = ''
        self.ChongZhiEndTime = ''
        self.ChongZhiRankOpen = 0
        self.OpenPayRebate = 0
        self.PayRebateStartTime = 0
        self.PayRebateEndTime = 0
        self.PayRebateRate = 0.0
        self.OpenWishingWell = 0
        self.WishingWellInTime = 0
        self.WishingWellOutTime = 0
        self.WishingWellOutDays = 0

    def load(self, row):
        fieldList = row.split()
        self.__ID__ = int(fieldList[0])
        self.Id = int(fieldList[0])
        self.StartTime = fieldList[2]
        self.StartTimeForExpLimit = fieldList[3]
        self.SelfIp = fieldList[4]
        self.PortForClient = int(fieldList[5])
        self.PortForGMI = int(fieldList[6])
        self.MemList = fieldList[7]
        self.MemOpen = int(fieldList[8])
        self.ThreadCount = int(fieldList[9])
        self.DBName = fieldList[10]
        self.DBUser = fieldList[11]
        self.DBPsw = fieldList[12]
        self.DBIp = fieldList[13]
        self.DBPort = int(fieldList[14])
        self.DBThreadCount = int(fieldList[15])
        self.MaxOnlinePlayingPlayer = int(fieldList[16])
        self.MaxOnlineQueuingPlayer = int(fieldList[17])
        self.MergeStatus = int(fieldList[18])
        self.MergeServerCount = int(fieldList[19])
        self.CDKeyOpen = int(fieldList[20])
        self.ChongZhiStartTime = fieldList[21]
        self.ChongZhiEndTime = fieldList[22]
        self.ChongZhiRankOpen = int(fieldList[23])
        self.OpenPayRebate = int(fieldList[24])
        self.PayRebateStartTime = int(fieldList[25])
        self.PayRebateEndTime = int(fieldList[26])
        self.PayRebateRate = float(fieldList[27])
        self.OpenWishingWell = int(fieldList[28])
        self.WishingWellInTime = int(fieldList[29])
        self.WishingWellOutTime = int(fieldList[30])
        self.WishingWellOutDays = int(fieldList[31])
