#!/usr/bin/python
# -*- coding: utf-8 -*-

BILLINGWORKMODE_PROJECT = 0#工程开发模式
BILLINGWORKMODE_BILLING = 1#线上正式SDK模式

VALIDATETYPE_TEST = 0#测试帐号
VALIDATETYPE_BILLING = 1#正式帐号

VALIDATERESULT_SUCCESS = 0#验证成功
VALIDATERESULT_FAILED = 1#验证失败