#!/usr/bin/python
# -*- coding: utf-8 -*-

PACKET_NULL = 0
PACKET_CG_LOGIN = 1
PACKET_GC_LOGIN_RET = 2
PACKET_CG_PING = 3
PACKET_GC_RET_PING = 4
PACKET_GC_LOGIN_QUEUE_STATUS = 5
PACKET_CG_CREATEROLE = 6
PACKET_GC_CREATEROLE_RET = 7
PACKET_CG_SELECTROLE = 8
PACKET_GC_SELECTROLE_RET = 9
PACKET_CG_REQ_RANDOMNAME = 10
PACKET_GC_RET_RANDOMNAME = 11
PACKET_CG_REQ_CHANGE_SCENE = 12
PACKET_GC_ENTER_SCENE = 13
PACKET_CG_ENTER_SCENE_OK = 14
PACKET_CG_CONNECTED_HEARTBEAT = 15
PACKET_GC_CONNECTED_HEARTBEAT = 16
PACKET_GC_NOTICE = 17
PACKET_GC_MISSION_SYNC_MISSIONLIST = 18
PACKET_CG_ACCEPTMISSION = 19
PACKET_GC_ACCEPTMISSION_RET = 20
PACKET_CG_COMPLETEMISSION = 21
PACKET_GC_COMPLETEMISSION_RET = 22
PACKET_CG_ABANDONMISSION = 23
PACKET_GC_ABANDONMISSION_RET = 24
PACKET_GC_MISSION_STATE = 25
PACKET_GC_MISSION_PARAM = 26
PACKET_GC_CREATE_PLAYER = 27
PACKET_GC_DELETE_OBJ = 28
PACKET_CG_SYNC_POS = 29
PACKET_GC_SYNC_POS = 30
PACKET_CG_MOVE = 31
PACKET_GC_MOVE = 32
PACKET_GC_STOP = 33
PACKET_MAX = 34